name: C++ conversion tests

on:
  push:
    paths:
    - 'cpptests/**.*'

jobs:
  build:

    runs-on: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      working-directory: cpptests
      run: sudo apt-get update && sudo apt-get install libeigen3-dev && mkdir bin
    - name: Configure
      working-directory: cpptests/bin
      run: cmake ..
    - name: Build
      working-directory: cpptests/bin
      run: make && make install
    - name: Basic Test
      working-directory: cpptests/bin
      run: |
        ./cppUncertainSCIMathDriver
