name: Publish Package
on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  upload_testpypi:
    name: Publish build to TestPyPI
    needs: [build, test]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/UncertainSCI
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: artifact
          path: dist

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist

  upload_pypi:
    name: Publish build to PyPI
    needs: [build, test, upload_testpypi]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/UncertainSCI
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: artifact
          path: dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
