name: Publish Package
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - 'v[0-9]+'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  publish-test:
    uses: ./.github/workflows/publish-test.yml

  upload_pypi:
    name: Publish build to PyPI
    needs: [lint, build, test, publish-test]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/UncertainSCI
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: uncertainsci-packages
          path: dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
