name: Publish Package (TestPyPI/dry run)
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - 'v[0-9]+*test*'
      - '*test*-v[0-9]+'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  upload_testpypi:
    name: Publish build to TestPyPI
    needs: [lint, build, test]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/UncertainSCI
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: uncertainsci-packages
          path: dist

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
