name: Test
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # optional, adds caching for faster builds

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install UncertainSCI
      run: |
        python -m pip install --upgrade pip
        pip install --editable .["dev"]

    - name: Run tests and compute coverage
      run: |
        pytest --cov=UncertainSCI

    - name: Upload coverage to coveralls.io
      continue-on-error: true
      run: |
        pip install coveralls
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.os }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Confirm coveralls.io reporting
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    
    steps:
    - name: Finish coveralls.io reporting
      continue-on-error: true
      run: |
        pip3 install --upgrade pip
        pip3 install --upgrade coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
